# Generated by Django 3.1.1 on 2020-12-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201021_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='SPE_ID',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='institute_registration_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
