# Generated by Django 3.1.1 on 2020-11-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_singleregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeration',
            name='Member_1',
            field=models.CharField(max_length=300),
        ),
    ]
