# Generated by Django 3.1.1 on 2020-11-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20201106_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singleregistration',
            name='Member_1',
            field=models.CharField(max_length=100),
        ),
    ]
