# Generated by Django 3.1.3 on 2020-12-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20201106_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='img_url',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
    ]
