# Generated by Django 3.1.1 on 2020-09-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200908_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='overview',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
