# Generated by Django 3.1.3 on 2020-12-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200929_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img_url',
            field=models.URLField(default='#'),
            preserve_default=False,
        ),
    ]
