# Generated by Django 3.1.1 on 2020-12-30 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
