# Generated by Django 3.1.3 on 2020-12-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagesForUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=100)),
                ('sender_email', models.CharField(max_length=120)),
                ('message', models.CharField(max_length=600)),
            ],
        ),
    ]
